---
- name: check bman installed
  stat: >
    path=/usr/local/{{ bman_tarball | basename | replace('.tar.gz','') }}
  register: bman_st

- name: get bman zip
  get_url: >
    url='{{ bman_tarball }}'
    dest='/tmp/'
  when: bman_st.stat.exists == False

- name: unpack bman zip  
  shell: "tar -zxvf /tmp/{{ bman_tarball | basename }} -C {{ bman_install_path }}"
  when: bman_st.stat.exists == False

- name: set /usr/local/bman symlink
  file: >
    src="/usr/local/{{ bman_tarball | basename | replace('.tar.gz','') }}"
    dest={{ bman_symlink }}
    state=link

- name: set /usr/local/bin/bman symlink
  file: >
    src='{{ bman_symlink }}/bin/fromdual_bman'
    dest={{ bman_bin_symlink }}
    state=link

- name: create bman config path
  file: >
    path={{ bman_config_path }}
    state=directory

- name: create bman configs
  template: >
    src=bman_config_template.j2
    dest='{{ bman_config_path }}/{{ item.file.name }}'
    owner=root
    mode=0400
  with_items: bman_config
  when: bman_config is defined

- name: set bman cronjobs
  cron: >
    name={{ item.name }}
    hour={{ item.hour }}
    minute={{ item.minute }}
    job='bman --config={{ bman_config_path }}/{{ item.config_file }} > /dev/null'
    user=root
    state=present
  with_items: bman_crons
  when: bman_crons is defined